### ISSUE TITLE
BUG: Viewport Size

### ISSUE THREAD

**Issue by deadbelly** [deadbelly/breathEZ#52]
**Describe the bug / point of concern**
We're failing an option Lighthouse check that indicates whether the app adjusts dynamically to the viewport width. We have code that should handle this but it either isn't working, or isn't working properly with Lighthouse. 

**Location / Steps To Reproduce**
1. Go to the App
2. Open dev tools
3. Run the lighthouse PWA audit
4. Scroll down to the viewport width test and see that it's grey (not red, but not green)

**Expected behavior**
Ideally this test should pass and give us a green check.

**Comment by thaomonster** [comment]
It is greyed out for the desktop version since PWA is mainly for mobile when we switch lighthouse over to check mobile fill it will become green.
